name: Run README notebook
on: push

jobs:

  run_notebook:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - run: |
          pip install nbconvert
          pip install --upgrade pip ipython ipykernel
          ipython kernel install --name "python3" --user
          pip install scikit-learn
          jupyter nbconvert --execute --to notebook --inplace README.ipynb
