name: Run README notebook
on: push

jobs:

  run_notebook:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install nbconvert
          jupyter nbconvert --execute --to notebook --inplace README.ipynb
